apiVersion: batch/v1
kind: Job
metadata:
  name: chatwoot-db-prepare
  namespace: chatwoot
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: chatwoot
      containers:
        - name: db-prepare
          image: chatwoot/chatwoot:v4.11.1
          command: ["bundle", "exec", "rails", "db:prepare"]
          envFrom:
            - secretRef:
                name: chatwoot-env
            - secretRef:
                name: chatwoot-secrets