apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secrets
  namespace: chatwoot
type: Opaque
stringData:
  SECRET_KEY_BASE: "CHANGEME_openssl_rand_hex_64"
  POSTGRES_PASSWORD: "CHANGEME_rds_password"
  REDIS_PASSWORD: dASD@#1115