apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secrets
  namespace: chatwoot
type: Opaque
stringData:
  SECRET_KEY_BASE: "CHANGEME_generate_openssl_rand_hex_64"
  POSTGRES_PASSWORD: "CHANGEME_db_password"
  # Se for usar SMTP, coloque aqui também:
  # SMTP_PASSWORD: "CHANGEME"