apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatwoot
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: chatwoot

  sources:
    - repoURL: https://chatwoot.github.io/charts
      chart: chatwoot
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/terraform/chatwoot-dev/app/chatwoot/values.yaml

    - repoURL: https://github.com/Marcusronney/Projeto_DevOPS_chatwoot_AWS.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true