apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatwoot-secrets
  namespace: chatwoot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: chatwoot-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: chatwoot/dev/app
        property: SECRET_KEY_BASE

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: chatwoot/dev/app
        property: POSTGRES_PASSWORD

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: chatwoot/dev/app
        property: REDIS_PASSWORD