web:
  startupProbe:
    enabled: true
    httpGet:
      path: /health
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  readinessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  livenessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 6